import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import java.io.File;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eldoran
 */
public class MainForm extends javax.swing.JFrame {
   
    int sec= 59;
    int minutes=0;
    int hours=0;
    
    public int initSec = 0;
    public int initMin = 0;
    public int initHour = 0;
   
             
    //delcaration of timer
    Timer timer = new  Timer(1000,new ActionListener(){
        
        public void actionPerformed(ActionEvent e){
            
        secTxt.setText(String.format("%02d", sec));       
        minTxt.setText(String.format("%02d", minutes));   
        hourTxt.setText(String.format("%02d", hours));   
            
        if (sec == 0){
            if (minutes ==0){
                if(hours==0){
                    timer.stop();
                    showTimerEndedDialog();
                }else{
                    hours --;
                    minutes = 60;
                }
            }else{
            minutes--;
            sec=59;
            }
        }else{ 
            sec--;
        }      
        }
    });      
       
        private void showTimerEndedDialog() {
        JOptionPane.showMessageDialog(this,
        "Timer has ended!",
        "Timer Alert",
        JOptionPane.INFORMATION_MESSAGE);
}
  
  
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        
    ((AbstractDocument) secTxt.getDocument()).setDocumentFilter(new DigitFilter(2));
    ((AbstractDocument) minTxt.getDocument()).setDocumentFilter(new DigitFilter(2));
    ((AbstractDocument) hourTxt.getDocument()).setDocumentFilter(new DigitFilter(2));
    }
    private  void initializeTime(){
        initSec = Integer.parseInt(secTxt.getText());
        initMin = Integer.parseInt(minTxt.getText());
        initHour = Integer.parseInt(hourTxt.getText());
        sec = initSec;         
        minutes = initMin;
        hours = initHour;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResetBtn = new javax.swing.JButton();
        StartBtn = new javax.swing.JButton();
        SecondsLbl1 = new javax.swing.JLabel();
        SecondsLbl2 = new javax.swing.JLabel();
        minTxt = new javax.swing.JTextField();
        secTxt = new javax.swing.JTextField();
        hourTxt = new javax.swing.JTextField();
        SetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Timer");

        ResetBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ResetBtn.setText("RESET");
        ResetBtn.setEnabled(false);
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        StartBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StartBtn.setText("START");
        StartBtn.setEnabled(false);
        StartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtnActionPerformed(evt);
            }
        });

        SecondsLbl1.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        SecondsLbl1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        SecondsLbl1.setText(":");
        SecondsLbl1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        SecondsLbl2.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        SecondsLbl2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        SecondsLbl2.setText(":");
        SecondsLbl2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        minTxt.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        minTxt.setText("00");
        minTxt.setVerifyInputWhenFocusTarget(false);
        minTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minTxtActionPerformed(evt);
            }
        });

        secTxt.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        secTxt.setText("00");
        secTxt.setVerifyInputWhenFocusTarget(false);
        secTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secTxtActionPerformed(evt);
            }
        });

        hourTxt.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        hourTxt.setText("00");
        hourTxt.setVerifyInputWhenFocusTarget(false);
        hourTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourTxtActionPerformed(evt);
            }
        });

        SetBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SetBtn.setText("SET");
        SetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hourTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecondsLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SecondsLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(secTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(hourTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SecondsLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(minTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SecondsLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(secTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void StartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtnActionPerformed
        // TODO add your handling code here:
        SetBtn.setEnabled(false);

        if (StartBtn.getText().equals("START")) {
                 //set the seconds    
                
             
                
                timer.start();
                StartBtn.setText("PAUSE");
        } else {
                SetBtn.setEnabled(true);

                StartBtn.setText("START");
                timer.stop();
        }
        
      
       
        
        
    }//GEN-LAST:event_StartBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        timer.stop();
             
        sec = initSec;         
        minutes = initMin;
        hours = initHour;
        
        secTxt.setText(String.format("%02d", sec));       
        minTxt.setText(String.format("%02d", minutes));  
        hourTxt.setText(String.format("%02d", hours)); 
        
        SetBtn.setEnabled(true);        
        StartBtn.setEnabled(false);
        ResetBtn.setEnabled(false);
        StartBtn.setText("START");
        
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void minTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minTxtActionPerformed

    private void secTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secTxtActionPerformed

    private void hourTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourTxtActionPerformed

    private void SetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetBtnActionPerformed
        // TODO add your handling code here:
        initializeTime();
        StartBtn.setEnabled(true);        
        ResetBtn.setEnabled(true);

    }//GEN-LAST:event_SetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
   
  private Clip clip;  // Clip object to control playback

// Method to play the alert sound
private void playAlertSound() {
    try {
        File soundFile = new File("sounds/alert_sound.wav");  // Adjust path and filename as needed
        AudioInputStream audioIn = AudioSystem.getAudioInputStream(soundFile);
        clip = AudioSystem.getClip();
        clip.open(audioIn);
        clip.start();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}

// Method to stop the alert sound
private void stopAlertSound() {
    if (clip != null && clip.isRunning()) {
        clip.stop();
        clip.close();
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetBtn;
    private javax.swing.JLabel SecondsLbl1;
    private javax.swing.JLabel SecondsLbl2;
    private javax.swing.JButton SetBtn;
    private javax.swing.JButton StartBtn;
    private javax.swing.JTextField hourTxt;
    private javax.swing.JTextField minTxt;
    private javax.swing.JTextField secTxt;
    // End of variables declaration//GEN-END:variables
}
